/** @type {Partial<import("typedoc").TypeDocOptions> & import("typedoc-plugin-markdown").PluginOptions} */
const config = {
  entryPoints: ["./lib/index.ts"],
  plugin: ["typedoc-plugin-markdown"],
  out: "docs-src/api",
  readme: "none",
  entryFileName: "index",
  groupReferencesByType: true,
  categorizeByGroup: true,
  groupOrder: ["Functions", "Interfaces", "Type Aliases"],
  categoryOrder: [
    "Environment",
    "Path",
    "File",
    "Logging",
    "Promise",
    "String",
    "Text",
    "Captcha",
    "SSH",
    "Aliyun OSS",
    "Qiniu OSS",
    "Type",
    "Debug",
    "Module",
    "Network",
  ],
  includeVersion: true,
  cleanOutputDir: true,
  excludePrivate: true,
  excludeProtected: true,
  excludeExternals: true,
  skipErrorChecking: true,
};

export default config;
